// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC95x7wfZ_sxZavsiuCGsFX-xGLx_IO9e0',
    appId: '1:734276112269:web:41b516942e05b42568b7c4',
    messagingSenderId: '734276112269',
    projectId: 'crud-32ef0',
    authDomain: 'crud-32ef0.firebaseapp.com',
    storageBucket: 'crud-32ef0.firebasestorage.app',
    measurementId: 'G-1R42N9C8E9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI2oabu9RPsrDGv0pJK01OCmnnDMfmp94',
    appId: '1:734276112269:android:252ea3d009a5162c68b7c4',
    messagingSenderId: '734276112269',
    projectId: 'crud-32ef0',
    storageBucket: 'crud-32ef0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8wQW3BLY6LTXiCAj7shsNFXAETSEP84k',
    appId: '1:734276112269:ios:5612739115be958a68b7c4',
    messagingSenderId: '734276112269',
    projectId: 'crud-32ef0',
    storageBucket: 'crud-32ef0.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8wQW3BLY6LTXiCAj7shsNFXAETSEP84k',
    appId: '1:734276112269:ios:5612739115be958a68b7c4',
    messagingSenderId: '734276112269',
    projectId: 'crud-32ef0',
    storageBucket: 'crud-32ef0.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC95x7wfZ_sxZavsiuCGsFX-xGLx_IO9e0',
    appId: '1:734276112269:web:be7242a341a8392168b7c4',
    messagingSenderId: '734276112269',
    projectId: 'crud-32ef0',
    authDomain: 'crud-32ef0.firebaseapp.com',
    storageBucket: 'crud-32ef0.firebasestorage.app',
    measurementId: 'G-XKB3L6DYLZ',
  );
}
